---
- name: Install multiple packages package
  hosts: webserver
  become: true
  tasks:
    - name: install unzip
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: install tree
      apt:
        name: tree
        state: present
        update_cache: yes

    - name: install httpd
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Copy index.html file
      copy:
        src: "/absolute/path/to/index.html"
        dest: "/var/www/html/index.html"

    - name: start httpd
      service:
        name: apache2
        state: started
