---
- name: Install multiple packages package
  hosts: web
  become: true

  tasks:
    - name: Ensure python3 is installed (for Ansible)
      raw: |
        which python3 || (apt-get update && apt-get install -y python3)
      changed_when: false

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install python3-apt
      apt:
        name: python3-apt
        state: present

    - name: Install required packages
      apt:
        name:
          - unzip
          - tree
          - apache2
        state: present

    - name: Copy index.html file
      copy:
        src: "index.html"
        dest: "/var/www/html/index.html"

    - name: Start and enable apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
